#!/bin/bash

yt-dlp -f 251 --remux-video mka -o "%(title)s - %(artist)s.%(ext)s" \
--add-metadata --embed-thumbnail --convert-thumb png \
--ppa "ThumbnailsConvertor+ffmpeg_o:-c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" \
"$1"
